





INSERT INTO stores (name, description, address, phone)
VALUES
    ('ElectroAptech', 'Electronics and gadgets store', '285 Doi CN', '1234567890');


INSERT INTO brands (name, description) VALUES
    ('Samsung', 'Offers products such as smartphones, TVs, washing machines, and home appliances.'),
    ('Apple', 'Known for its smartphones, tablets, laptops, and other innovative technology products.'),
    ('Sony', 'Recognized for products such as TVs, cameras, and audio equipment.'),
    ('LG', 'Known for its TVs, washing machines, refrigerators, and other home appliances.'),
    ('Panasonic', 'Provides products such as refrigerators, washing machines, and consumer electronics.'),
    ('Sharp', 'Offers TVs, air conditioners, and other home appliances.'),
    ('Bosch', 'Famous for home appliances such as washing machines, microwaves, and dishwashers.'),
    ('Toshiba', 'Provides products such as refrigerators, washing machines, and other electronics.'),
    ('Aqua', 'A brand under Haier, offering refrigerators, washing machines, and other home appliances.'),
    ('Xiaomi', 'Provides smartphones, smart home devices, and other technology products.'),
    ('Huawei', 'Known for smartphones and other technology devices.'),
    ('Dell', 'Offers laptops, desktops, and accessories.'),
    ('HP', 'Famous for computers, printers, and office equipment.'),
    ('Lenovo', 'Provides laptops, desktops, and other electronic devices.'),
    ('Asus', 'Offers laptops, motherboards, and accessories.'),
    ('MSI', 'Known for gaming laptops and computer components.'),
    ('Sunhouse', 'Known for affordable and practical home appliances.'),
    ('Kangaroo', 'Offers a wide range of home appliances with innovative features.');


INSERT INTO products (name, description, price, price_sale, category_id, subcategory_id, brand_id, quantity, store_id, avatar_product)
VALUES
('iPhone 13', 'Latest model with improved battery life and camera.', 699.99, 649.99,1,1, (SELECT brand_id FROM brands WHERE name = 'Apple'),150,1,'storage/images/iphone13_1.jpg'),
('iPhone 13 Pro Max', 'Max variant with the largest display and top features.', 999.99, 949.99,1,1, (SELECT brand_id FROM brands WHERE name = 'Apple'),60,1,'storage/images/iphone_13_pro_max_1.jpg'),
('iPhone 14', 'Latest iPhone with improved camera and performance.', 799.99, 749.99,1,1, (SELECT brand_id FROM brands WHERE name = 'Apple'),150,1,'storage/images/iphone14_1.jpg'),
('iPhone 14 Pro Max', 'Large screen iPhone with top-tier performance and camera capabilities.', 1099.99, 1049.99,1,1, (SELECT brand_id FROM brands WHERE name = 'Apple'),60,1,'storage/images/iphone_14_pro_max_1.jpg'),
('iPhone 15', 'The latest iPhone model with advanced features.', 1199.99, 1149.99,1,1, (SELECT brand_id FROM brands WHERE name = 'Apple'),100,1,'storage/images/iphone15_1.jpg'),
('Samsung Galaxy S23', 'Flagship smartphone with high-end specifications.', 799.99, 749.99,1,1, (SELECT brand_id FROM brands WHERE name = 'Samsung'),80,1,'storage/images/samsung_galaxy_s23_1.jpg'),
('Samsung Galaxy A54', 'Mid-range smartphone with a good balance of performance and features.', 299.99, 249.99,1,1, (SELECT brand_id FROM brands WHERE name = 'Samsung'),100,1,'storage/images/samsung_galaxy_a54_1.jpg'),
('Samsung QLED TV 65"', 'High-definition QLED TV with vibrant colors and deep blacks.', 1299.99, 1199.99,1,2, (SELECT brand_id FROM brands WHERE name = 'Samsung'),25,1,'storage/images/samsung_qled_tv_65_1.jpg'),
('Samsung Frame TV 50"', 'Stylish TV that doubles as a piece of art.', 999.99, 949.99,1,2, (SELECT brand_id FROM brands WHERE name = 'Samsung'),20,1,'storage/images/samsung_frame_tv_50_1.jpg'),
('LG OLED TV 55"', 'OLED TV with exceptional contrast and color accuracy.', 1499.99, 1399.99,1,2, (SELECT brand_id FROM brands WHERE name = 'LG'),10,1,'storage/images/lg_oled_tv_55_1.jpg'),
('LG Nanocell TV 65"', 'NanoCell technology for enhanced color and clarity.', 1399.99, 1299.99,1,2, (SELECT brand_id FROM brands WHERE name = 'LG'),20,1,'storage/images/lg_nanocell_tv_65_1.jpg'),
('Asus ZenBook 14', 'Ultrabook with a sleek design and strong performance.', 1199.99, 1099.99,1,3, (SELECT brand_id FROM brands WHERE name = 'Asus'),45,1,'storage/images/asus_zenbook_14_1.jpg'),
('Asus TUF Gaming A15', 'Gaming laptop with durable build and high performance.', 1299.99, 1199.99,1,3, (SELECT brand_id FROM brands WHERE name = 'Asus'),50,1,'storage/images/asus_tuf_gaming_a15_1.jpg'),
('Lenovo ThinkPad X1 Carbon', 'Business laptop known for its durability and performance.', 1499.99, 1399.99,1,3, (SELECT brand_id FROM brands WHERE name = 'Lenovo'),30,1,'storage/images/lenovo_thinkpad_x1_carbon_1.jpg'),
('Lenovo Yoga 9i', 'Convertible laptop with a high-resolution display and versatile functionality.', 1299.99, 1199.99,1,3, (SELECT brand_id FROM brands WHERE name = 'Lenovo'),40,1,'storage/images/lenovo_yoga_9i_1.jpg'),
('Panasonic NR-BV280QSVN', 'Panasonic NR-BV280QSVN refrigerator with Inverter technology for energy saving.', 899.99, 849.99,2,4, (SELECT brand_id FROM brands WHERE name = 'Panasonic'),50,1,'storage/images/panasonic_nr_1.jpg'),
('Panasonic NR-BA228PKV1', 'Panasonic NR-BA228PKV1 refrigerator with modern and convenient design.', 799.99, 749.99,2,4, (SELECT brand_id FROM brands WHERE name = 'Panasonic'),60,1,'storage/images/ba228pkv1_1.jpg'),
('Toshiba GR-RS682WE-PMV(06)-XK', 'Toshiba GR-RS682WE-PMV(06)-XK refrigerator with optimal cooling technology and energy saving.', 1099.99, 1049.99,2,4, (SELECT brand_id FROM brands WHERE name = 'Toshiba'),30,1,'storage/images/rs682we_1.jpg'),
('Toshiba GR-AG66VA(XK)', 'Toshiba GR-AG66VA(XK) refrigerator with luxurious design and large capacity.', 999.99, 949.99,2,4, (SELECT brand_id FROM brands WHERE name = 'Toshiba'),35,1,'storage/images/ag66va(xk)_1.jpg'),
('Toshiba AW-B1000GV', 'Toshiba AW-B1000GV offers a spacious drum and multiple wash programs for effective cleaning.', 550.00, 500.00,2,5, (SELECT brand_id FROM brands WHERE name = 'Toshiba'),25,1,'storage/images/b1000gv_1.jpg'),
('Toshiba TW-BH85S2V', 'Toshiba TW-BH85S2V provides high washing efficiency with smart technology and various settings.', 600.00, 550.00,2,5, (SELECT brand_id FROM brands WHERE name = 'Toshiba'),20,1,'storage/images/bh85s2v_1.jpg'),
('Samsung WW90J54E0BW/SV', 'Samsung WW90J54E0BW/SV features a large capacity and advanced cleaning technology for thorough washing.', 700.00, 650.00,2,5, (SELECT brand_id FROM brands WHERE name = 'Samsung'),15,1,'storage/images/ww90j54e0bwsv_1.jpg'),
('Samsung WA10J5710SG/SV', 'Samsung WA10J5710SG/SV is known for its robust build and powerful washing performance.', 650.00, 600.00,2,5, (SELECT brand_id FROM brands WHERE name = 'Samsung'),18,1,'storage/images/wa10j5710sgsv_1.jpg'),
('Panasonic MC-CL563', 'Compact design easy to use vacuum cleaner.', 179.99, 169.99,2,6, (SELECT brand_id FROM brands WHERE name = 'Panasonic'),60,1,'storage/images/cl563_1.jpg'),
('Panasonic MC-CL305', 'Vacuum cleaner with effective dust filtering feature.', 159.99, 149.99,2,6, (SELECT brand_id FROM brands WHERE name = 'Panasonic'),55,1,'storage/images/cl305_1.jpg'),
('Toshiba VC-PG514', 'Vacuum cleaner with advanced dust filtering technology.', 219.99, 209.99,2,6, (SELECT brand_id FROM brands WHERE name = 'Toshiba'),40,1,'storage/images/toshiba_vc_pg514_1.jpg'),
('Toshiba VC-WF500', 'Equipped with HEPA filter and adjustable suction power.', 229.99, 219.99,2,6, (SELECT brand_id FROM brands WHERE name = 'Toshiba'),45,1,'storage/images/toshiba_1.jpg'),
('Toshiba RAS-13N3KV', 'Large capacity air conditioner for quick cooling.', 589.99, 569.99,3,7, (SELECT brand_id FROM brands WHERE name = 'Toshiba'),20,1,'storage/images/13n3kv_1.jpg'),
('Toshiba RAS-09BKCV', 'Air conditioner with sleek design and high performance.', 439.99, 419.99,3,7, (SELECT brand_id FROM brands WHERE name = 'Toshiba'),45,1,'storage/images/09bkcv_1.jpg'),
('LG LS-H09VNA', 'Air conditioner with Dual Inverter technology for quiet operation.', 469.99, 449.99,3,7, (SELECT brand_id FROM brands WHERE name = 'LG'),35,1,'storage/images/h09vna_1.jpg'),
('LG LS-H12VNA', 'Large capacity air conditioner for efficient cooling in larger rooms.', 569.99, 549.99,3,7, (SELECT brand_id FROM brands WHERE name = 'LG'),30,1,'storage/images/h12vna_1.jpg'),
('Samsung AX50R9080S', 'Air cooler with advanced cooling technology and modern design.', 149.99, 139.99,3,8, (SELECT brand_id FROM brands WHERE name = 'Samsung'),15,1,'storage/images/may_loc_khong_khi_samsung_ax90r7080_1.jpg'),
('Samsung VF-R21', 'Stand fan with wide cooling range and adjustable speed.', 79.99, 74.99,3,8, (SELECT brand_id FROM brands WHERE name = 'Samsung'),30,1,'storage/images/samsung_vf_r21_1.jpg'),
('LG WF-181', 'Stand fan with powerful motor and adjustable airflow.', 74.99, 69.99,3,8, (SELECT brand_id FROM brands WHERE name = 'LG'),45,1,'storage/images/lg_air_1.jpg'),
('LG WF-232', 'Wall fan with high power and efficient cooling.', 94.99, 89.99,3,8, (SELECT brand_id FROM brands WHERE name = 'LG'),20,1,'storage/images/lg_wf_232_1.jpg'),
('LG XBOOM SK10Y', 'Soundbar with Dolby Atmos technology and high-quality audio.', 699.99, 669.99,4,9, (SELECT brand_id FROM brands WHERE name = 'LG'),20,1,'storage/images/sk10y_1.jpg'),
('LG XBOOM RL4', 'Bluetooth speaker with large power and dynamic sound.', 129.99, 119.99,4,9, (SELECT brand_id FROM brands WHERE name = 'LG'),40,1,'storage/images/rl4_1.jpg'),
('Samsung HW-Q950A', 'Soundbar with Dolby Atmos technology and 11.1.4 channel surround sound.', 1399.99, 1349.99,4,9, (SELECT brand_id FROM brands WHERE name = 'Samsung'),10,1,'storage/images/q950a_1.jpg'),
('Samsung Sound Tower MX-T70', 'Bluetooth speaker with high power and LED light effects.', 299.99, 279.99,4,9, (SELECT brand_id FROM brands WHERE name = 'Samsung'),30,1,'storage/images/mx_t70_1.jpg'),
('Apple AirPods Pro', 'Wireless in-ear headphones with noise cancellation and Siri integration.', 249.99, 229.99,4,10, (SELECT brand_id FROM brands WHERE name = 'Apple'),30,1,'storage/images/airportpro_1.jpg'),
('Apple AirPods Max', 'Over-ear headphones with high-quality sound and active noise cancellation.', 549.99, 529.99,4,10, (SELECT brand_id FROM brands WHERE name = 'Apple'),10,1,'storage/images/airportpromax_1.jpg'),
('Sony WF-1000XM4', 'Wireless in-ear headphones with active noise cancellation and excellent sound quality.', 279.99, 259.99,4,10, (SELECT brand_id FROM brands WHERE name = 'Sony'),30,1,'storage/images/1000xm5_1.jpg'),
('Sony WH-H910N', 'Over-ear headphones with noise cancellation and clear sound.', 199.99, 179.99,4,10, (SELECT brand_id FROM brands WHERE name = 'Sony'),25,1,'storage/images/h910n_1.jpg'),
('Sunhouse Modern LED Wall Light', 'Modern LED wall light with elegant design and effective illumination.', 79.99, 69.99,5,11, (SELECT brand_id FROM brands WHERE name = 'Sunhouse'),25,1,'storage/images/sunhouse_modern_led_wall_light_1.jpg'),
('Sunhouse Classic Wall Light', 'Classic LED wall light with warm illumination and energy efficiency.', 89.99, 79.99,5,11, (SELECT brand_id FROM brands WHERE name = 'Sunhouse'),20,1,'storage/images/sunhouse_classic_wall_light_1.jpg'),
('Kangaroo Elegant Wall Light', 'Kangaroo wall light with a sophisticated design and soft illumination.', 89.99, 79.99,5,11, (SELECT brand_id FROM brands WHERE name = 'Kangaroo'),15,1,'storage/images/kangaroo_elegant_wall_light_1.jpg'),
('Kangaroo LED Wall Lamp', 'Kangaroo LED wall lamp with powerful illumination and high performance.', 99.99, 89.99,5,11, (SELECT brand_id FROM brands WHERE name = 'Kangaroo'),18,1,'storage/images/kangaroo_led_wall_lamp_1.jpg'),
('Kangaroo Table Lamp', 'Elegant table lamp with energy-saving LED light and stylish finish.', 59.99, 54.99,5,12, (SELECT brand_id FROM brands WHERE name = 'Kangaroo'),15,1,'storage/images/kangaroo_table_lamp_1.jpg'),
('Xiaomi Table Lamp', 'Smart table lamp with adjustable color temperature and remote control.', 79.99, 74.99,5,12, (SELECT brand_id FROM brands WHERE name = 'Xiaomi'),18,1,'storage/images/xiaomi_lamp_1.jpg'),
('Panasonic Table Lamp', 'High-quality table lamp with classic design and long-lasting LED.', 89.99, 84.99,5,12, (SELECT brand_id FROM brands WHERE name = 'Panasonic'),10,1,'storage/images/panasonic_table_lamp_1.jpg');

INSERT INTO product_images (product_id, image_url) VALUES
(1,'storage/images/iphone13_2.jpg'),
(1,'storage/images/iphone13_3.jpg'),
(1,'storage/images/iphone13_4.jpg'),
(2,'storage/images/iphone_13_pro_max_2.jpg'),
(2,'storage/images/iphone_13_pro_max_3.jpg'),
(2,'storage/images/iphone_13_pro_max_4.jpg'),
(3,'storage/images/iphone14_2.jpg'),
(3,'storage/images/iphone14_3.jpg'),
(3,'storage/images/iphone14_4.jpg'),
(4,'storage/images/iphone_14_pro_max_2.jpg'),
(4,'storage/images/iphone_14_pro_max_3.jpg'),
(4,'storage/images/iphone_14_pro_max_4.jpg'),
(5,'storage/images/iphone15_2.jpg'),
(5,'storage/images/iphone15_3.jpg'),
(5,'storage/images/iphone15_4.jpg'),
(6,'storage/images/samsung_galaxy_s23_2.jpg'),
(6,'storage/images/samsung_galaxy_s23_3.jpg'),
(6,'storage/images/samsung_galaxy_s23_4.jpg'),
(7,'storage/images/samsung_galaxy_a54_2.jpg'),
(7,'storage/images/samsung_galaxy_a54_3.jpg'),
(7,'storage/images/samsung_galaxy_a54_4.jpg'),
(8,'storage/images/samsung_qled_tv_65_2.jpg'),
(8,'storage/images/samsung_qled_tv_65_3.jpg'),
(8,'storage/images/samsung_qled_tv_65_4.jpg'),
(9,'storage/images/samsung_frame_tv_50_2.jpg'),
(9,'storage/images/samsung_frame_tv_50_3.jpg'),
(9,'storage/images/samsung_frame_tv_50_4.jpg'),
(10,'storage/images/lg_oled_tv_55_2.jpg'),
(10,'storage/images/lg_oled_tv_55_3.jpg'),
(10,'storage/images/lg_oled_tv_55_4.jpg'),
(11,'storage/images/lg_nanocell_tv_65_2.jpg'),
(11,'storage/images/lg_nanocell_tv_65_3.jpg'),
(11,'storage/images/lg_nanocell_tv_65_4.jpg'),
(12,'storage/images/asus_zenbook_14_2.jpg'),
(12,'storage/images/asus_zenbook_14_3.jpg'),
(12,'storage/images/asus_zenbook_14_4.jpg'),
(13,'storage/images/asus_tuf_gaming_a15_2.jpg'),
(13,'storage/images/asus_tuf_gaming_a15_3.jpg'),
(13,'storage/images/asus_tuf_gaming_a15_4.jpg'),
(14,'storage/images/lenovo_thinkpad_x1_carbon_2.jpg'),
(14,'storage/images/lenovo_thinkpad_x1_carbon_3.jpg'),
(14,'storage/images/lenovo_thinkpad_x1_carbon_4.jpg'),
(15,'storage/images/lenovo_yoga_9i_2.jpg'),
(15,'storage/images/lenovo_yoga_9i_3.jpg'),
(15,'storage/images/lenovo_yoga_9i_4.jpg'),
(16,'storage/images/panasonic_nr_2.jpg'),
(16,'storage/images/panasonic_nr_3.jpg'),
(16,'storage/images/panasonic_nr_4.jpg'),
(17,'storage/images/ba228pkv1_2.jpg'),
(17,'storage/images/ba228pkv1_3.jpg'),
(17,'storage/images/ba228pkv1_4.jpg'),
(18,'storage/images/rs682we_2.jpg'),
(18,'storage/images/rs682we_3.jpg'),
(18,'storage/images/rs682we_4.jpg'),
(19,'storage/images/ag66va(xk)_2.jpg'),
(19,'storage/images/ag66va(xk)_3.jpg'),
(19,'storage/images/ag66va(xk)_4.jpg'),
(20,'storage/images/b1000gv_2.jpg'),
(20,'storage/images/b1000gv_3.jpg'),
(20,'storage/images/b1000gv_4.jpg'),
(21,'storage/images/bh85s2v_2.jpg'),
(21,'storage/images/bh85s2v_3.jpg'),
(21,'storage/images/bh85s2v_4.jpg'),
(22,'storage/images/ww90j54e0bwsv_2.jpg'),
(22,'storage/images/ww90j54e0bwsv_3.jpg'),
(22,'storage/images/ww90j54e0bwsv_4.jpg'),
(23,'storage/images/wa10j5710sgsv_2.jpg'),
(23,'storage/images/wa10j5710sgsv_3.jpg'),
(23,'storage/images/wa10j5710sgsv_4.jpg'),
(24,'storage/images/cl563_2.jpg'),
(24,'storage/images/cl563_3.jpg'),
(24,'storage/images/cl563_4.jpg'),
(25,'storage/images/cl305_2.jpg'),
(25,'storage/images/cl305_3.jpg'),
(25,'storage/images/cl305_4.jpg'),
(26,'storage/images/toshiba_vc_pg514_2.jpg'),
(26,'storage/images/toshiba_vc_pg514_3.jpg'),
(26,'storage/images/toshiba_vc_pg514_4.jpg'),
(27,'storage/images/toshiba_2.jpg'),
(27,'storage/images/toshiba_3.jpg'),
(27,'storage/images/toshiba_4.jpg'),
(28,'storage/images/13n3kv_2.jpg'),
(28,'storage/images/13n3kv_3.jpg'),
(28,'storage/images/13n3kv_4.jpg'),
(29,'storage/images/09bkcv_2.jpg'),
(29,'storage/images/09bkcv_3.jpg'),
(29,'storage/images/09bkcv_4.jpg'),
(30,'storage/images/h09vna_2.jpg'),
(30,'storage/images/h09vna_3.jpg'),
(30,'storage/images/h09vna_4.jpg'),
(31,'storage/images/h12vna_2.jpg'),
(31,'storage/images/h12vna_3.jpg'),
(31,'storage/images/h12vna_4.jpg'),
(32,'storage/images/may_loc_khong_khi_samsung_ax90r7080_2.jpg'),
(32,'storage/images/may_loc_khong_khi_samsung_ax90r7080_3.jpg'),
(32,'storage/images/may_loc_khong_khi_samsung_ax90r7080_4.jpg'),
(33,'storage/images/samsung_vf_r21_2.jpg'),
(33,'storage/images/samsung_vf_r21_3.jpg'),
(33,'storage/images/samsung_vf_r21_4.jpg'),
(34,'storage/images/lg_air_2.jpg'),
(34,'storage/images/lg_air_3.jpg'),
(34,'storage/images/lg_air_4.jpg'),
(35,'storage/images/lg_wf_232_2.jpg'),
(35,'storage/images/lg_wf_232_3.jpg'),
(35,'storage/images/lg_wf_232_4.jpg'),
(36,'storage/images/sk10y_2.jpg'),
(36,'storage/images/sk10y_3.jpg'),
(36,'storage/images/sk10y_4.jpg'),
(37,'storage/images/rl4_2.jpg'),
(37,'storage/images/rl4_3.jpg'),
(37,'storage/images/rl4_4.jpg'),
(38,'storage/images/q950a_2.jpg'),
(38,'storage/images/q950a_3.jpg'),
(38,'storage/images/q950a_4.jpg'),
(39,'storage/images/mx_t70_2.jpg'),
(39,'storage/images/mx_t70_3.jpg'),
(39,'storage/images/mx_t70_4.jpg'),
(40,'storage/images/airportpro_2.jpg'),
(40,'storage/images/airportpro_3.jpg'),
(40,'storage/images/airportpro_4.jpg'),
(41,'storage/images/airportpromax_2.jpg'),
(41,'storage/images/airportpromax_3.jpg'),
(41,'storage/images/airportpromax_4.jpg'),
(42,'storage/images/1000xm5_2.jpg'),
(42,'storage/images/1000xm5_3.jpg'),
(42,'storage/images/1000xm5_4.jpg'),
(43,'storage/images/h910n_2.jpg'),
(43,'storage/images/h910n_3.jpg'),
(43,'storage/images/h910n_4.jpg'),
(44,'storage/images/sunhouse_modern_led_wall_light_2.jpg'),
(44,'storage/images/sunhouse_modern_led_wall_light_3.jpg'),
(44,'storage/images/sunhouse_modern_led_wall_light_4.jpg'),
(45,'storage/images/sunhouse_classic_wall_light_2.jpg'),
(45,'storage/images/sunhouse_classic_wall_light_3.jpg'),
(45,'storage/images/sunhouse_classic_wall_light_4.jpg'),
(46,'storage/images/kangaroo_elegant_wall_light_2.jpg'),
(46,'storage/images/kangaroo_elegant_wall_light_3.jpg'),
(46,'storage/images/kangaroo_elegant_wall_light_4.jpg'),
(47,'storage/images/kangaroo_led_wall_lamp_2.jpg'),
(47,'storage/images/kangaroo_led_wall_lamp_3.jpg'),
(47,'storage/images/kangaroo_led_wall_lamp_4.jpg'),
(48,'storage/images/kangaroo_table_lamp_2.jpg'),
(48,'storage/images/kangaroo_table_lamp_3.jpg'),
(48,'storage/images/kangaroo_table_lamp_4.jpg'),
(49,'storage/images/xiaomi_lamp_2.jpg'),
(49,'storage/images/xiaomi_lamp_3.jpg'),
(49,'storage/images/xiaomi_lamp_4.jpg'),
(50,'storage/images/panasonic_table_lamp_2.jpg'),
(50,'storage/images/panasonic_table_lamp_3.jpg'),
(50,'storage/images/panasonic_table_lamp_4.jpg');




INSERT INTO `users` (`id`, `name`, `password`, `email`, `phone`, `address`, `role`, `created_at`, `updated_at`) VALUES
(1, 'admin', '$2y$10$7x88liiEN.VgUHeM3pdx8.zdumcMLCyeKFei1Ao0Icai351IMADzq', 'admin@com.vn', '0333333333', 'Ha noi', 'admin', '2024-08-19 03:56:58', '2024-08-19 03:56:58');

INSERT INTO `carts` (`cart_id`, `user_id`, `total_price`, `created_at`, `updated_at`) VALUES
(1, 1, 0.00, '2024-08-19 03:56:58', '2024-08-19 03:56:58');
